_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.2
layer_kwargs:
  alpha: 0.7000000000000001
  theta: 0.1
  shared_weights: true
learning_rate: 0.006698342208290751
weight_decay: 1.2962902155339495e-07
_gradient_clip_val: 0.5
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCNII-S2N
