_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.2
layer_kwargs:
  alpha: 0.6
  theta: 0.1
  shared_weights: true
learning_rate: 0.001
weight_decay: 3.879141580272101e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: GCNII-S2N
