_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.2
layer_kwargs:
  alpha: 0.6
  theta: 1.1
  shared_weights: true
learning_rate: 0.005995215640784903
weight_decay: 4.964182949984042e-07
_gradient_clip_val: 0.1
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCNII-S2N
