_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.0
layer_kwargs:
  alpha: 0.2
  theta: 1.0
  shared_weights: true
learning_rate: 0.0013624855637873485
weight_decay: 1.9878109864009363e-08
_gradient_clip_val: 0.2
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCNII-S2N
