_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
layer_kwargs:
  alpha: 0.8
  theta: 0.1
  shared_weights: false
learning_rate: 0.005
weight_decay: 1.309966577555948e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: GCNII-S2N
