_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 3
use_bn: true
use_skip: false
dropout_channels: 0.1
dropout_edges: 0.0
layer_kwargs:
  alpha: 0.8
  theta: 2.0
  shared_weights: true
learning_rate: 0.001
weight_decay: 1.928605121050183e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
subname: GCNII-S2N
