_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.2
learning_rate: 0.005459686516116742
weight_decay: 1.0324016236489359e-09
_gradient_clip_val: 0.4
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-S2N
