_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.1
dropout_edges: 0.1
learning_rate: 0.0005
weight_decay: 3.209180174807717e-08
_gradient_clip_val: 0.1
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
subname: GCN-S2N
