_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.30000000000000004
learning_rate: 0.0027469542392616207
weight_decay: 3.187794900913421e-07
_gradient_clip_val: 0.2
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-S2N
