_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.4
layer_kwargs:
  alpha: 0.5
  theta: 0.5
  shared_weights: true
learning_rate: 0.0008716603823794119
weight_decay: 1.1721827843003949e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCNII-S2N
