_target_: data.SubgraphDataModule

defaults:
  - common_datamodule.yaml

dataset_name: "HPOMetab"

use_s2n: True
s2n_target_matrix: "adjacent_with_self_loops"
post_edge_normalize: "standardize_then_trunc_thres_max_linear"
post_edge_normalize_arg_1: 4.0
post_edge_normalize_arg_2: 1.0

# Will be inherited to the trainer, model
_max_epochs: 2500
_is_multi_labels: False