_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.4
learning_rate: 0.0031438669140471743
weight_decay: 1.5920102991160425e-07
_gradient_clip_val: 0.1
subname: GCN-${datamodule.subgraph_batching}
