_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.1
learning_rate: 0.0007186451405667469
weight_decay: 1.239785362158022e-07
_gradient_clip_val: 0.5
subname: GCN-${datamodule.subgraph_batching}
