_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GCNConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.001
weight_decay: 4.5861187247411003e-07
_gradient_clip_val: 0.0
subname: GCN-${datamodule.subgraph_batching}
