_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.0
learning_rate: 0.004560822964301878
weight_decay: 2.1265888316519655e-09
_gradient_clip_val: 0.30000000000000004
subname: GCN-${datamodule.subgraph_batching}
