_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: ["Linear", "GCNConv"]
num_layers: [2, 1]
use_bn: True
use_skip: False
dropout_channels: 0.4
dropout_edges: 0.3

learning_rate: 0.001
weight_decay: 0.00000045861187247411
_gradient_clip_val: 0.0

subname: "GCN-${datamodule.subgraph_batching}"
