_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: ["Linear", "GCNConv"]
num_layers: [2, 1]
use_bn: True
use_skip: False
dropout_channels: 0.0
dropout_edges: 0.5

learning_rate: 0.005
weight_decay: 0.000000995649109942547
_gradient_clip_val: 0.1

subname: "GCN-${datamodule.subgraph_batching}"
