_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.2
learning_rate: 0.005141302668914148
weight_decay: 5.626292096276186e-08
_gradient_clip_val: 0.30000000000000004
subname: GCN-${datamodule.subgraph_batching}
