_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: ["Linear", "GCNConv"]
num_layers: [2, 2]
use_bn: True
use_skip: False
dropout_channels: 0.4
dropout_edges: 0.4

learning_rate: 0.005
weight_decay: 0.0000000251662229001333
_gradient_clip_val: 0.0

subname: "GCN-${datamodule.subgraph_batching}"
