_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.1
learning_rate: 0.001155466090195086
weight_decay: 4.668038992982043e-07
_gradient_clip_val: 0.0
subname: GCN-${datamodule.subgraph_batching}
