_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.0005
weight_decay: 1.1284941856045706e-09
_gradient_clip_val: 0.4
subname: GCN-${datamodule.subgraph_batching}
