_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: GCNConv
num_layers: 2
use_bn: True
use_skip: False
dropout_channels: 0.1
dropout_edges: 0.0

learning_rate: 0.001
weight_decay: 0.00001
_gradient_clip_val: 0.0

subname: "GCN-${datamodule.subgraph_batching}-${datamodule.transform_args[0]}"
