_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.1
learning_rate: 0.0030187428197389864
weight_decay: 9.261772265353933e-07
_gradient_clip_val: 0.4
subname: GCN-${datamodule.subgraph_batching}
