_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.5
learning_rate: 0.0064683419023396265
weight_decay: 2.507922281980491e-07
_gradient_clip_val: 0.30000000000000004
subname: GCN-${datamodule.subgraph_batching}
