_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
learning_rate: 0.009818801669761401
weight_decay: 6.760151473522678e-09
_gradient_clip_val: 0.30000000000000004
subname: GCN-${datamodule.subgraph_batching}
