_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.30000000000000004
learning_rate: 0.003707668249401796
weight_decay: 7.358439433225614e-08
_gradient_clip_val: 0.5
subname: GCN-${datamodule.subgraph_batching}
