_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.4
learning_rate: 0.0026376422861242774
weight_decay: 3.986228788078938e-08
_gradient_clip_val: 0.30000000000000004
subname: GCN-${datamodule.subgraph_batching}
