_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: ["Linear", "GCNConv"]
num_layers: [2, 2]
use_bn: True
use_skip: False
dropout_channels: 0.5
dropout_edges: 0.5

learning_rate: 0.0005
weight_decay: 0.00000000892635867432401
_gradient_clip_val: 0.3

subname: "GCN-${datamodule.subgraph_batching}"
