_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.5
learning_rate: 0.0035202928164288294
weight_decay: 1.4291547153584525e-09
_gradient_clip_val: 0.2
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCNConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-SUB-S2N
