_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.0013930406073214938
weight_decay: 8.929211233355213e-07
_gradient_clip_val: 0.30000000000000004
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCNConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-SUB-S2N
