_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.2
learning_rate: 0.0005799646703476106
weight_decay: 1.745468842689941e-09
_gradient_clip_val: 0.5
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCNConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-SUB-S2N
