_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCNConv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.2
learning_rate: 0.00190625950689961
weight_decay: 2.8117769890848674e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCNConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GCN-SUB-S2N
