_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GATConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.5
layer_kwargs:
  heads: 1
  dropout: 0.5
learning_rate: 0.005
weight_decay: 2.7720239790004056e-09
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
