_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.0
layer_kwargs:
  heads: 8
learning_rate: 0.003437508485431018
weight_decay: 7.157082977238308e-09
_gradient_clip_val: 0.5
subname: GAT-${datamodule.subgraph_batching}
