_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.1
layer_kwargs:
  heads: 8
learning_rate: 0.002357312104766979
weight_decay: 1.9168378523322182e-08
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
