_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.5
layer_kwargs:
  heads: 8
learning_rate: 0.005
weight_decay: 3.7976956196698675e-08
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
