_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.4
layer_kwargs:
  heads: 8
learning_rate: 0.0043552812038368015
weight_decay: 2.4728873777315672e-09
_gradient_clip_val: 0.4
subname: GAT-${datamodule.subgraph_batching}
