_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: LINKX
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.2
layer_kwargs:
  num_edge_layers: 1
  num_node_layers: 1
learning_rate: 0.001
weight_decay: 2.553978533354773e-09
_gradient_clip_val: 0.0
subname: ILINKX-${datamodule.subgraph_batching}
