_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: LINKX
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.30000000000000004
layer_kwargs:
  num_edge_layers: 1
  num_node_layers: 1
learning_rate: 0.0005
weight_decay: 9.760403967293037e-07
_gradient_clip_val: 0.0
subname: ILINKX-${datamodule.subgraph_batching}
