_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: LINKX
num_layers: 3
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.0
layer_kwargs:
  num_edge_layers: 1
  num_node_layers: 1
learning_rate: 0.001
weight_decay: 5.482516382294391e-08
_gradient_clip_val: 0.0
subname: ILINKX-${datamodule.subgraph_batching}
