_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.1
layer_kwargs:
  eps: 0.1
learning_rate: 0.006386389945953746
weight_decay: 1.5292797802607943e-08
_gradient_clip_val: 0.2
subname: FA-${datamodule.subgraph_batching}
