_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.5
layer_kwargs:
  eps: 0.4
learning_rate: 0.005211518707933086
weight_decay: 1.5238667639461434e-09
_gradient_clip_val: 0.2
subname: FA-${datamodule.subgraph_batching}
