_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- FAConv
num_layers:
- 2
- 3
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.2
layer_kwargs:
  eps: 0.2
  dropout: 0.5
learning_rate: 0.0005
weight_decay: 3.837852094832735e-08
_gradient_clip_val: 0.0
subname: FA-${datamodule.subgraph_batching}
