_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.4
layer_kwargs:
  eps: 0.2
learning_rate: 0.004736810234931064
weight_decay: 7.061703639501118e-09
_gradient_clip_val: 0.5
subname: FA-${datamodule.subgraph_batching}
