_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.4
layer_kwargs:
  eps: 0.2
learning_rate: 0.005352166482707812
weight_decay: 1.15322906351235e-07
_gradient_clip_val: 0.0
subname: FA-${datamodule.subgraph_batching}
