_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: GINConv
num_layers: 1
use_bn: True
use_skip: False
dropout_channels: 0.1
dropout_edges: 0.0
layer_kwargs: {
  train_eps: True,
}

learning_rate: 0.001
weight_decay: 3.5917e-9
_gradient_clip_val: 0.0

sub_node_num_layers: 1
sub_node_encoder_aggr: "sum"

subname: GIN-S2N
