_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GINConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.0
layer_kwargs:
  heads: 8
learning_rate: 0.0030539093265053293
weight_decay: 4.6455992285068085e-08
_gradient_clip_val: 0.1
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GIN-S2N
