_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GINConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
layer_kwargs:
  train_eps: true
learning_rate: 0.001
weight_decay: 2.1827969521910524e-09
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: GIN-S2N
