_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 2
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.5
learning_rate: 0.0006040558628647296
weight_decay: 2.999778185446577e-07
_gradient_clip_val: 0.1
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: SAGEConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: SAGE-SUB-S2N
