_target_: data.SubgraphDataModule
defaults:
- common_datamodule.yaml
dataset_name: HPOMetab
embedding_type: glass
subgraph_batching: connected
use_s2n: false
_max_epochs: 2500
_is_multi_labels: false
