_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.4
learning_rate: 0.005
weight_decay: 4.3512943201800556e-08
_gradient_clip_val: 0.0
subname: SAGE-${datamodule.subgraph_batching}
