_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
learning_rate: 0.0005
weight_decay: 3.6384871645925643e-09
_gradient_clip_val: 0.0
subname: SAGE-${datamodule.subgraph_batching}
