_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- SAGEConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.5
learning_rate: 0.001
weight_decay: 1.7087357978764263e-08
_gradient_clip_val: 0.0
subname: SAGE-${datamodule.subgraph_batching}
