_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.1
learning_rate: 0.0006729222436882799
weight_decay: 3.147268848868461e-09
_gradient_clip_val: 0.5
subname: SAGE-${datamodule.subgraph_batching}
