_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.0018177090475891328
weight_decay: 1.7752731098204342e-07
_gradient_clip_val: 0.1
subname: SAGE-${datamodule.subgraph_batching}
