_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- SAGEConv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
learning_rate: 0.005
weight_decay: 1.2957355357225804e-07
_gradient_clip_val: 0.0
subname: SAGE-${datamodule.subgraph_batching}
