_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GCN2Conv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
layer_kwargs:
  alpha: 0.6
  theta: 1.2000000000000002
  shared_weights: true
learning_rate: 0.0005
weight_decay: 4.4607819978116095e-09
_gradient_clip_val: 0.5
subname: GCNII-${datamodule.subgraph_batching}
