_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.5
layer_kwargs:
  alpha: 0.4
  theta: 0.7000000000000001
  shared_weights: false
learning_rate: 0.008773750985589033
weight_decay: 4.826395023351838e-07
_gradient_clip_val: 0.4
subname: GCNII-${datamodule.subgraph_batching}
