_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.4
layer_kwargs:
  alpha: 0.2
  theta: 0.2
  shared_weights: true
learning_rate: 0.0014093678095211735
weight_decay: 1.7449118107835592e-09
_gradient_clip_val: 0.2
subname: GCNII-${datamodule.subgraph_batching}
