_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GCN2Conv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.30000000000000004
layer_kwargs:
  alpha: 0.1
  theta: 0.6
  shared_weights: false
learning_rate: 0.001
weight_decay: 3.3175281602139543e-09
_gradient_clip_val: 0.0
subname: GCNII-${datamodule.subgraph_batching}
