_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.4
layer_kwargs:
  alpha: 0.6
  theta: 0.1
  shared_weights: true
learning_rate: 0.0011630075787080335
weight_decay: 3.941615455572743e-08
_gradient_clip_val: 0.4
subname: GCNII-${datamodule.subgraph_batching}
