_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.4
layer_kwargs:
  alpha: 0.9
  theta: 1.1
  shared_weights: false
learning_rate: 0.00484897501019643
weight_decay: 6.300175189597069e-08
_gradient_clip_val: 0.2
subname: GCNII-${datamodule.subgraph_batching}
