_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
layer_kwargs:
  alpha: 0.1
  theta: 0.1
  shared_weights: false
learning_rate: 0.0067216562323730656
weight_decay: 1.095709399426651e-08
_gradient_clip_val: 0.30000000000000004
subname: GCNII-${datamodule.subgraph_batching}
