_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.4
layer_kwargs:
  eps: 0.5
learning_rate: 0.006906125457916246
weight_decay: 3.489994442871674e-08
_gradient_clip_val: 0.0
subname: FA-${datamodule.subgraph_batching}
