_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- FAConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
layer_kwargs:
  eps: 0.30000000000000004
  dropout: 0.5
learning_rate: 0.001
weight_decay: 1.7417447044047612e-09
_gradient_clip_val: 0.0
subname: FA-${datamodule.subgraph_batching}
