_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.0
layer_kwargs:
  eps: 0.2
learning_rate: 0.004560589538582139
weight_decay: 2.8740604344713847e-09
_gradient_clip_val: 0.30000000000000004
subname: FA-${datamodule.subgraph_batching}
