_target_: data.SubgraphDataModule
defaults:
  - common_datamodule.yaml
  - common_datamodule_co.yaml
coarsening_ratio: 0.2
dataset_name: PPIBP
use_s2n: true
subgraph_batching: sub_s2n
s2n_use_sub_edge_index: true
s2n_mapping_matrix_type: unnormalized
s2n_set_sub_x_weight: null
s2n_target_matrix: wl_kernel
post_edge_normalize: standardize_then_trunc_thres_max_linear
post_edge_normalize_arg_1: 1.5
post_edge_normalize_arg_2: 1.5
_max_epochs: 400
_is_multi_labels: false
