_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.0
learning_rate: 0.0010139296545802735
weight_decay: 6.653018265950169e-08
_gradient_clip_val: 0.5
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.1
  theta: 0.5
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.4
  theta: 1.3000000000000003
  shared_weights: false
subname: GCNII-SUB-S2N
