_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.30000000000000004
learning_rate: 0.0007443120765147927
weight_decay: 4.997205095722281e-09
_gradient_clip_val: 0.0
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.6
  theta: 0.4
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.7000000000000001
  theta: 0.2
  shared_weights: true
subname: GCNII-SUB-S2N
