_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.4
learning_rate: 0.0027934729106091336
weight_decay: 1.4050174347577883e-09
_gradient_clip_val: 0.0
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.9
  theta: 0.6
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.9
  theta: 0.9
  shared_weights: true
subname: GCNII-SUB-S2N
