_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.0
learning_rate: 0.005609258453584633
weight_decay: 4.886961094181224e-09
_gradient_clip_val: 0.0
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.7000000000000001
  theta: 0.5
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.5
  theta: 1.7000000000000002
  shared_weights: false
subname: GCNII-SUB-S2N
