_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: LINKX
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.30000000000000004
layer_kwargs:
  num_edge_layers: 1
  num_node_layers: 1
learning_rate: 0.0005
weight_decay: 5.754787702445336e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
subname: ILINKX-S2N
