_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: LINKX
num_layers: 3
use_bn: false
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
layer_kwargs:
  num_edge_layers: 1
  num_node_layers: 1
learning_rate: 0.001
weight_decay: 2.1004702888360674e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: ILINKX-S2N
