_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: GCNConv
num_layers: 2
use_bn: True
use_skip: False
dropout_channels: 0.2
dropout_edges: 0.3

learning_rate: 0.001
weight_decay: 3.08E-09
_gradient_clip_val: 0.1

sub_node_num_layers: 2
sub_node_encoder_aggr: "sum"

subname: GCN