_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: GCNConv
num_layers: 1
use_bn: True
use_skip: False
dropout_channels: 0.2
dropout_edges: 0.3

learning_rate: 0.001
weight_decay: 1.30E-08
_gradient_clip_val: 0.3

sub_node_num_layers: 1
sub_node_encoder_aggr: "sum"

subname: GCN
