_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: LINKX
num_layers: 1
use_bn: False
use_skip: False
dropout_channels: 0.0
dropout_edges: 0.0
layer_kwargs: {
  num_edge_layers: 1,
  num_node_layers: 1,
}

learning_rate: 0.001
weight_decay: 2.02E-08
_gradient_clip_val: 0.3

sub_node_num_layers: 2
sub_node_encoder_aggr: "sum"

subname: I-LINKX
