_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.5
learning_rate: 0.008109674456048733
weight_decay: 4.5396244367670377e-07
_gradient_clip_val: 0.1
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GATConv
layer_kwargs:
  heads: 8
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GAT-SUB-S2N
