_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATv2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.2
learning_rate: 0.00953850164245461
weight_decay: 1.6212690800146955e-08
_gradient_clip_val: 0.5
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GATv2Conv
layer_kwargs:
  heads: 8
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GATv2-SUB-S2N
