_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 2
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.5
learning_rate: 0.002990788518107873
weight_decay: 1.7555949074541595e-08
_gradient_clip_val: 0.30000000000000004
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GATConv
layer_kwargs:
  heads: 8
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GAT-SUB-S2N
