_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GINConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.4
layer_kwargs:
  train_eps: true
learning_rate: 0.001
weight_decay: 4.318332288209044e-08
_gradient_clip_val: 0.3
subname: GIN-${datamodule.subgraph_batching}
