_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GINConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
layer_kwargs:
  train_eps: true
learning_rate: 0.001
weight_decay: 8.688580811765415e-07
_gradient_clip_val: 0.0
subname: GIN-${datamodule.subgraph_batching}
