_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GINConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.1
layer_kwargs:
  eps: 0.0
  train_eps: true
learning_rate: 0.003321908537096067
weight_decay: 2.836821618713765e-09
_gradient_clip_val: 0.4
subname: GIN-${datamodule.subgraph_batching}
