_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: false
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.5
learning_rate: 0.000722186779291023
weight_decay: 4.2536984198073075e-07
_gradient_clip_val: 0.1
subname: SAGE-${datamodule.subgraph_batching}
