_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.1
dropout_edges: 0.4
learning_rate: 0.0018099106118051815
weight_decay: 1.024668606065048e-08
_gradient_clip_val: 0.30000000000000004
subname: SAGE-${datamodule.subgraph_batching}
