_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
learning_rate: 0.0021701401464385545
weight_decay: 3.6102182562689337e-09
_gradient_clip_val: 0.2
subname: SAGE-${datamodule.subgraph_batching}
