_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.1
learning_rate: 0.0029085174338515955
weight_decay: 3.7063316698934833e-09
_gradient_clip_val: 0.4
subname: SAGE-${datamodule.subgraph_batching}
