_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- SAGEConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.0
learning_rate: 0.001
weight_decay: 2.972127808415728e-09
_gradient_clip_val: 0.3
subname: SAGE-${datamodule.subgraph_batching}
