_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- SAGEConv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.5
learning_rate: 0.0005
weight_decay: 9.73692405026446e-07
_gradient_clip_val: 0.0
subname: SAGE-${datamodule.subgraph_batching}
