_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.2
learning_rate: 0.000823635338326614
weight_decay: 9.794074568035975e-09
_gradient_clip_val: 0.5
subname: SAGE-${datamodule.subgraph_batching}
