_target_: data.SubgraphDataModule

defaults:
  - common_datamodule.yaml

dataset_name: "PPIBP"
embedding_type: "gin"  # gin, graphsaint_gcn, glass

subgraph_batching: "separated"
use_s2n: False

# Will be inherited to the trainer, model
_max_epochs: 400
_is_multi_labels: False