_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.1
layer_kwargs:
  eps: 0.5
learning_rate: 0.00977013758561168
weight_decay: 2.19895086607826e-09
_gradient_clip_val: 0.4
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: FAConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: 0.4
  alpha: null
  theta: null
  shared_weights: null
subname: FA-SUB-S2N
