_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.0
layer_kwargs:
  eps: 0.5
learning_rate: 0.0027288611328689883
weight_decay: 9.76851077887435e-07
_gradient_clip_val: 0.1
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: FAConv
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: 0.30000000000000004
  alpha: null
  theta: null
  shared_weights: null
subname: FA-SUB-S2N
