_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.2
learning_rate: 0.0009675500663455247
weight_decay: 1.2515840688757756e-07
_gradient_clip_val: 0.5
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.4
  theta: 0.2
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.9
  theta: 0.30000000000000004
  shared_weights: false
subname: GCNII-SUB-S2N
