_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.1
learning_rate: 0.005667161318096924
weight_decay: 2.9576083601827563e-08
_gradient_clip_val: 0.4
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.1
  theta: 0.9
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.7000000000000001
  theta: 1.2000000000000002
  shared_weights: true
subname: GCNII-SUB-S2N
