_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.006381851988888763
weight_decay: 9.305568387164351e-08
_gradient_clip_val: 0.5
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.5
  theta: 0.5
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.8
  theta: 0.7000000000000001
  shared_weights: true
subname: GCNII-SUB-S2N
