_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
learning_rate: 0.0005745252241856178
weight_decay: 3.29785162674474e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.7000000000000001
  theta: 0.2
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.9
  theta: 0.7000000000000001
  shared_weights: false
subname: GCNII-SUB-S2N
