_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.1
learning_rate: 0.00924775519183082
weight_decay: 2.7354260295032597e-09
_gradient_clip_val: 0.1
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.4
  theta: 1.0
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.1
  theta: 0.30000000000000004
  shared_weights: true
subname: GCNII-SUB-S2N
