_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
learning_rate: 0.0015030473223832292
weight_decay: 2.5313785963670297e-09
_gradient_clip_val: 0.1
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.4
  theta: 0.8
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.5
  theta: 1.9000000000000001
  shared_weights: false
subname: GCNII-SUB-S2N
