_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.4
learning_rate: 0.008025291093481489
weight_decay: 1.5870190477952337e-07
_gradient_clip_val: 0.2
sub_node_num_layers: 2
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.1
  theta: 0.5
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.6
  theta: 1.5000000000000002
  shared_weights: true
subname: GCNII-SUB-S2N
