_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.5
learning_rate: 0.007174715509107871
weight_decay: 3.258031644761426e-08
_gradient_clip_val: 0.5
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.9
  theta: 1.6
  shared_weights: false
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.9
  theta: 0.9
  shared_weights: false
subname: GCNII-SUB-S2N
