_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.5
learning_rate: 0.001398560179294623
weight_decay: 2.616340156122374e-08
_gradient_clip_val: 0.1
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
sub_node_encoder_name: GCN2Conv
layer_kwargs:
  alpha: 0.9
  theta: 1.1
  shared_weights: true
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: 0.1
  theta: 1.0
  shared_weights: false
subname: GCNII-SUB-S2N
