_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GINConv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.4
layer_kwargs:
  train_eps: true
learning_rate: 0.005
weight_decay: 4.2340504685720664e-07
_gradient_clip_val: 0.0
subname: GIN-${datamodule.subgraph_batching}
