_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GINConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
layer_kwargs:
  heads: 8
learning_rate: 0.0012209332362746082
weight_decay: 6.277426376020999e-09
_gradient_clip_val: 0.2
subname: GIN-${datamodule.subgraph_batching}
