_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GINConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.1
layer_kwargs:
  train_eps: true
learning_rate: 0.001
weight_decay: 3.672689221913809e-07
_gradient_clip_val: 0.0
subname: GIN-${datamodule.subgraph_batching}
