_target_: data.SubgraphDataModule
defaults:
  - common_datamodule.yaml
dataset_name: EMUser
use_s2n: true
s2n_mapping_matrix_type: unnormalized
s2n_set_sub_x_weight: null
s2n_target_matrix: wl_kernel
post_edge_normalize: standardize_then_trunc_thres_max_linear
post_edge_normalize_arg_1: 2.0
post_edge_normalize_arg_2: 1.0
_max_epochs: 1200
_is_multi_labels: false
