dataset_path: ${dataset_path} # dataset_path is specified in config.yaml
dataset_subname: "${datamodule.dataset_name}"

use_sparse_tensor: False
pre_add_self_loops: False  # for GATConv with SparseTensor
verbose: 2
num_workers: 0

# NOTE: common args when use_s2n=True
edge_thres: 0.0  # important
use_consistent_processing: True
s2n_target_matrix: "adjacent_no_self_loops"
s2n_is_weighted: True

# NOTE: common args when use_s2n=False
batch_size: null
subgraph_batching: null  # separated, connected

# NOTE: common args when replace_x_with_wl4pattern=True
# type of which is (int, str), e.g., (0, "color"), (1, "cluster")
replace_x_with_wl4pattern: False
wl4pattern_args: [null, null]