dataset_path: ${dataset_path} # dataset_path is specified in config.yaml
dataset_subname: "${datamodule.dataset_name}-${datamodule.custom_splits}"

use_sparse_tensor: False
pre_add_self_loops: False  # for GATConv with SparseTensor
verbose: 2
num_workers: 0

embedding_type: glass  # gin, graphsaint_gcn, glass

# NOTE: common args when use_s2n=True
edge_thres: 0.0  # important
use_consistent_processing: True
s2n_set_sub_x_weight: null
s2n_target_matrix: adjacent_with_self_loops
s2n_add_sub_x_wl: False
s2n_is_weighted: True
post_edge_normalize_arg_1: null
post_edge_normalize_arg_2: null

# NOTE: common args when use_s2n=False
batch_size: null
subgraph_batching: null  # separated, connected

# NOTE: common args when replace_x_with_wl4pattern=True
# type of which is (int, str), e.g., (0, "color"), (1, "cluster")
replace_x_with_wl4pattern: False
wl4pattern_args: [ null, null ]

# NOTE: for sensitivity analysis by a number of training samples
# Default splits:
#   PPIBP: [0, 1272, 160], total=1591, test=0.1, train=0.8
#   HPONeuro: [0, 3204, 400], total=4000, test=0.1, train=0.8
#   HPOMetab: [0, 1921, 244], total=2400, test=0.1, train=0.8
#   EMUser: [0, 226, 49], total=324, test=0.15, train=0.7
# Recommended splits with the form of [num_start, num_train, num_val]:
#   PPIBP, HPONeuro, HPOMetab: [0, 0.8, 0.1], [0.1, 0.7, 0.1], ..., [0.7, 0.1, 0.1]
#   EMUser: [0, 0.7, 0.15], [0.1, 0.6, 0.15], ..., [0.6, 0.1, 0.15]
# Recommended splits with the form of [num_train_per_class]:
#   [5], [10], [20], [40]
custom_splits: null
num_training_tails_to_tile_per_class: null