dataset_subname: "${datamodule.dataset_name}_${datamodule.ba_m}"

# WL specific args
num_subgraphs: 1500
subgraph_size: 10
wl_hop_to_use: null  # NOTE: important
s2n_transform: "SliceYByIndex"
s2n_transform_args: [null]  # args for SliceYByIndex. NOTE: very important
wl_max_hop: 4
wl_x_type_for_hists: "cluster"  # color, cluster
wl_num_color_clusters: null
wl_num_hist_clusters: 2

# BA specific args
ba_seed: 42
ba_n: 10000
ba_m: 8  # 8, 10, 15, 20, 25
num_channels_global: 64  # for wl_ba, wl_er, ...
