_target_: data.SubgraphDataModule

dataset_name: "CutRatio"
dataset_path: ${dataset_path} # dataset_path is specified in config.yaml
embedding_type: "graphsaint_gcn"  # gin, graphsaint_gcn

use_s2n: True
edge_thres: 0.0  # important
use_consistent_processing: False
edge_normalize: "standardize_then_trunc_thres_max_linear"
edge_normalize_arg_1: 0.000
edge_normalize_arg_2: null
s2n_target_matrix: "adjacent_no_self_loops"
s2n_is_weighted: Tru

batch_size: 128  # for use_s2n=False

use_sparse_tensor: False
pre_add_self_loops: False  # for GATConv

verbose: 2
num_workers: 0

# Will be inherited to the trainer, model
_max_epochs: 1500
_is_multi_labels: False