_target_: data.SubgraphDataModule

defaults:
  - common_datamodule.yaml
  - common_wlks.yaml

dataset_name: "WLKSRandomTree"
embedding_type: "no_embedding"

use_s2n: True
s2n_mapping_matrix_type: "sqrt_d_node_div_d_sub"  # unnormalized, sqrt_d_node_div_d_sub, 1_div_sqrt_num_nodes_in_sub
post_edge_normalize: "standardize_then_trunc_thres_max_linear"
post_edge_normalize_arg_1: 0.000
post_edge_normalize_arg_2: null

# Will be inherited to the trainer, model
_max_epochs: 500
_is_multi_labels: False

