_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATv2Conv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.0
layer_kwargs:
  heads: 8
learning_rate: 0.005680081922923273
weight_decay: 2.807105386588027e-07
_gradient_clip_val: 0.0
subname: GATv2-${datamodule.subgraph_batching}
