_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATv2Conv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.5
layer_kwargs:
  heads: 8
learning_rate: 0.0019958304655823505
weight_decay: 5.1658579430347066e-09
_gradient_clip_val: 0.2
subname: GATv2-${datamodule.subgraph_batching}
