_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 2
use_bn: true
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.5
layer_kwargs:
  heads: 8
learning_rate: 0.006056713898117767
weight_decay: 5.011950721313157e-09
_gradient_clip_val: 0.2
subname: GAT-${datamodule.subgraph_batching}
