_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.5
layer_kwargs:
  heads: 8
learning_rate: 0.0014191803704265008
weight_decay: 3.341943747806106e-08
_gradient_clip_val: 0.30000000000000004
subname: GAT-${datamodule.subgraph_batching}
