_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GATConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.5
layer_kwargs:
  heads: 1
  dropout: 0.2
learning_rate: 0.001
weight_decay: 7.785823986255537e-07
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
