_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GATConv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.30000000000000004
dropout_edges: 0.5
layer_kwargs:
  heads: 1
  dropout: 0.30000000000000004
learning_rate: 0.005
weight_decay: 3.229413590553297e-07
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
