_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GATConv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.1
layer_kwargs:
  heads: 1
  dropout: 0.4
learning_rate: 0.005
weight_decay: 9.59946578001935e-07
_gradient_clip_val: 0.0
subname: GAT-${datamodule.subgraph_batching}
