_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.1
layer_kwargs:
  heads: 8
learning_rate: 0.009608503463662307
weight_decay: 7.324897874839982e-08
_gradient_clip_val: 0.2
subname: GAT-${datamodule.subgraph_batching}
