_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: false
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.0
learning_rate: 0.0085746718381667
weight_decay: 3.6953262719555664e-08
_gradient_clip_val: 0.4
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: SAGE-S2N
