_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: SAGEConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.0
learning_rate: 0.001
weight_decay: 1.2127593775358908e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: SAGE-S2N
