_target_: data.SubgraphDataModule
defaults:
- common_datamodule.yaml
- common_datamodule_co.yaml
coarsening_ratio: 0.4
dataset_name: PPIBP
use_s2n: true
s2n_mapping_matrix_type: unnormalized
s2n_set_sub_x_weight: null
s2n_target_matrix: adjacent_with_self_loops
post_edge_normalize: standardize_then_trunc_thres_max_linear
post_edge_normalize_arg_1: 2.25
post_edge_normalize_arg_2: 0.5
_max_epochs: 400
_is_multi_labels: false
