_target_: data.SubgraphDataModule

defaults:
  - common_datamodule.yaml

dataset_name: "PPIBP"

use_s2n: True
s2n_target_matrix: null
edge_normalize: "standardize_then_trunc_thres_max_linear"
edge_normalize_arg_1: 3.5
edge_normalize_arg_2: 2.0

# Will be inherited to the trainer, model
_max_epochs: 400
_is_multi_labels: False