_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: true
use_skip: false
dropout_channels: 0.0
dropout_edges: 0.2
layer_kwargs:
  eps: 0.4
  dropout: 0.0
learning_rate: 0.005
weight_decay: 9.414264352346748e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: FA-S2N
