_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.2
dropout_edges: 0.2
layer_kwargs:
  eps: 0.5
learning_rate: 0.0016051871572406483
weight_decay: 5.530255638108315e-09
_gradient_clip_val: 0.2
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: FA-S2N
