_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.1
dropout_edges: 0.30000000000000004
layer_kwargs:
  eps: 0.1
learning_rate: 0.0033531905667898644
weight_decay: 2.0230935281875724e-08
_gradient_clip_val: 0.5
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: FA-S2N
