_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 3
use_bn: true
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.1
layer_kwargs:
  eps: 0.5
  dropout: 0.2
learning_rate: 0.001
weight_decay: 2.070368059347248e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: FA-S2N
