_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: FAConv
num_layers: 1
use_bn: true
use_skip: false
dropout_channels: 0.5
dropout_edges: 0.5
layer_kwargs:
  eps: 0.5
  dropout: 0.5
learning_rate: 0.001
weight_decay: 1.4158053876891435e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 1
sub_node_encoder_aggr: sum
subname: FA-S2N
