_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: "Linear"
num_layers: 4
use_bn: True
use_skip: False
dropout_channels: 0.0
dropout_edges: 0.0

learning_rate: 0.001
weight_decay: 0.00001
_gradient_clip_val: 0.0

# datamodule.wl4pattern_args = (wl_step_to_use, wl_type_to_use),
#  the type of which is (int, str), e.g., (0, "color"), (1, "cluster")
subname: "MLPWL-${datamodule.subgraph_batching}-${datamodule.wl4pattern_args[1]}-${datamodule.wl4pattern_args[0]}"
