_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: true
dropout_channels: 0.5
dropout_edges: 0.30000000000000004
layer_kwargs:
  alpha: 0.1
  theta: 0.2
  shared_weights: true
learning_rate: 0.007838328552278612
weight_decay: 5.25516008142247e-07
_gradient_clip_val: 0.4
subname: GCNII-${datamodule.subgraph_batching}
