_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GCN2Conv
num_layers:
- 2
- 2
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.4
layer_kwargs:
  alpha: 0.2
  theta: 0.1
  shared_weights: true
learning_rate: 0.0005
weight_decay: 2.9220420312860108e-09
_gradient_clip_val: 0.0
subname: GCNII-${datamodule.subgraph_batching}
