_target_: model.GraphNeuralModel

defaults:
  - common_model.yaml

encoder_layer_name: ["Linear", "GCN2Conv"]
num_layers: [2, 2]
use_bn: True
use_skip: False
dropout_channels: 0.1
dropout_edges: 0.0
layer_kwargs: {
  alpha: 0.5,
  theta: 1.0,
  shared_weights: True,
}

learning_rate: 0.001
weight_decay: 0.00001
_gradient_clip_val: 0.0

subname: "GCNII-${datamodule.subgraph_batching}"
