_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GCN2Conv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.5
layer_kwargs:
  alpha: 0.2
  theta: 0.7000000000000001
  shared_weights: false
learning_rate: 0.009154373106368033
weight_decay: 4.118315148901638e-07
_gradient_clip_val: 0.4
subname: GCNII-${datamodule.subgraph_batching}
