_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name:
- Linear
- GCN2Conv
num_layers:
- 2
- 1
use_bn: true
use_skip: false
dropout_channels: 0.4
dropout_edges: 0.30000000000000004
layer_kwargs:
  alpha: 0.30000000000000004
  theta: 0.9
  shared_weights: true
learning_rate: 0.0005
weight_decay: 1.475042377229817e-09
_gradient_clip_val: 0.0
subname: GCNII-${datamodule.subgraph_batching}
