_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.4
dropout_edges: 0.2
layer_kwargs:
  heads: 8
learning_rate: 0.005
weight_decay: 1.8776358274999522e-07
_gradient_clip_val: 0.5
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: GAT-S2N
