_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.1
layer_kwargs:
  heads: 8
learning_rate: 0.004113896481398577
weight_decay: 1.1137638528619763e-07
_gradient_clip_val: 0.1
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GAT-S2N
