_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATv2Conv
num_layers: 2
use_bn: false
use_skip: false
dropout_channels: 0.2
dropout_edges: 0.0
layer_kwargs:
  heads: 8
learning_rate: 0.005162417797407132
weight_decay: 3.653192919185725e-07
_gradient_clip_val: 0.5
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GATv2-S2N
