_target_: model.GraphNeuralModel
defaults:
  - common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.0
dropout_edges: 0.0
layer_kwargs:
  heads: 8
learning_rate: 0.001
weight_decay: 1.205540227601915e-07
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
subname: GAT-S2N
