_target_: model.GraphNeuralModel
defaults:
- common_model.yaml
encoder_layer_name: GATConv
num_layers: 1
use_bn: true
use_skip: true
dropout_channels: 0.30000000000000004
dropout_edges: 0.2
layer_kwargs:
  heads: 8
learning_rate: 0.0008131187715874692
weight_decay: 1.4793069205712836e-08
_gradient_clip_val: 0.0
sub_node_num_layers: 0
sub_node_encoder_aggr: sum
sub_node_encoder_layer_kwargs:
  heads: 8
  eps: null
  alpha: null
  theta: null
  shared_weights: null
subname: GAT-S2N
